### ISSUE TITLE
Slim Application Error The application could not run because of the following error:

### ISSUE THREAD

**Issue by dgnzcn** [wizardg/paintstrap#11]
Hi, How can i fix this issue? i am on localhost.

```
Slim Application Error
The application could not run because of the following error:

Details

Type: Twig_Error_Loader
Message: Unable to find template "en/footer_col3.html" (looked into: /Library/WebServer/Documents/paintstrap-master/templates) in "en/footer.html" at line 20.
File: /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Loader/Filesystem.php
Line: 198
Trace

#0 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Loader/Filesystem.php(134): Twig_Loader_Filesystem->findTemplate('en/footer_col3....')
#1 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Environment.php(266): Twig_Loader_Filesystem->getCacheKey('en/footer_col3....')
#2 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Environment.php(313): Twig_Environment->getTemplateClass('en/footer_col3....', NULL)
#3 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Environment.php(321) : eval()'d code(56): Twig_Environment->loadTemplate('en/footer_col3....')
#4 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(265): __TwigTemplate_f8d525e2c5aa7c2127fe53dda651007a->doDisplay(Array, Array)
#5 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(239): Twig_Template->displayWithErrorHandling(Array, Array)
#6 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Environment.php(321) : eval()'d code(417): Twig_Template->display(Array)
#7 [internal function]: __TwigTemplate_6722b58e0148679d59bd649812efc59f->block_footer(Array, Array)
#8 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(134): call_user_func(Array, Array, Array)
#9 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Environment.php(321) : eval()'d code(136): Twig_Template->displayBlock('footer', Array, Array)
#10 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(265): __TwigTemplate_66698b401ff55c717a8b82cb09922bf8->doDisplay(Array, Array)
#11 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(239): Twig_Template->displayWithErrorHandling(Array, Array)
#12 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Environment.php(321) : eval()'d code(29): Twig_Template->display(Array, Array)
#13 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(265): __TwigTemplate_6722b58e0148679d59bd649812efc59f->doDisplay(Array, Array)
#14 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(239): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /Library/WebServer/Documents/paintstrap-master/vendor/Twig/Template.php(250): Twig_Template->display(Array)
#16 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Extras/Views/Twig.php(99): Twig_Template->render(Array)
#17 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/View.php(195): Slim\Extras\Views\Twig->render('en/index.html')
#18 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/View.php(182): Slim\View->fetch('en/index.html')
#19 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Slim.php(672): Slim\View->display('en/index.html')
#20 /Library/WebServer/Documents/paintstrap-master/index.php(59): Slim\Slim->render('en/index.html', Array)
#21 /Library/WebServer/Documents/paintstrap-master/index.php(27): index(Object(Slim\Slim), 'en')
#22 [internal function]: {closure}()
#23 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Router.php(172): call_user_func_array(Object(Closure), Array)
#24 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Slim.php(1222): Slim\Router->dispatch(Object(Slim\Route))
#25 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#26 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#27 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#28 /Library/WebServer/Documents/paintstrap-master/vendor/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#29 /Library/WebServer/Documents/paintstrap-master/index.php(325): Slim\Slim->run()
#30 {main}
```

**Comment by wizardg** [comment]
Hi,

Please rename footer_col3.html.sample to footer_col3.html

The same as previously mentioned,
config.sample
.htaccess.sample
templates/en/footer_col3.html.sample
templates/en/footer_link.html.sample
templates/ja/footer_col3.html.sample
templates/ja/footer_link.html.sample
